# Generated by Django 5.0.3 on 2024-03-26 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videosCenter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thumbnails',
            old_name='videos',
            new_name='video',
        ),
    ]
