# Generated by Django 5.0.3 on 2024-03-31 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videosCenter', '0002_rename_videos_thumbnails_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='publishing_datetime',
            new_name='published_time',
        ),
    ]
