# Generated by Django 5.0.3 on 2024-03-31 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosCenter', '0003_rename_publishing_datetime_videos_published_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnails',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='videosCenter.videos'),
        ),
    ]
